export const depotTags = [
  { key: "Python", label: "Python" },
  { key: "Java", label: "Java" },
  { key: "JavaScript", label: "JavaScript" },
  { key: "Ruby", label: "Ruby" },
  { key: "PHP", label: "PHP" },
  { key: "C#", label: "C#" },
  { key: "C++", label: "C++" },
  { key: "C", label: "C" },
  { key: "Web Development", label: "Web Development" },
  { key: "Mobile Development", label: "Mobile Development" },
  { key: "Data Science", label: "Data Science" },
  { key: "Machine Learning", label: "Machine Learning" },
  { key: "Artificial Intelligence", label: "Artificial Intelligence" },
  { key: "Cyber Security", label: "Cyber Security" },
  { key: "Cloud Computing", label: "Cloud Computing" },
  { key: "DevOps", label: "DevOps" },
  { key: "Game Development", label: "Game Development" },
  { key: "Internet of Things (IoT)", label: "Internet of Things (IoT)" },
  { key: "Blockchain", label: "Blockchain" },
  { key: "Robotics", label: "Robotics" },
];
